# Auto-generated schema from season 2025

MATCHES_COLUMNS = {
    "group": {"data_type": "text", "nullable": True},
    "id": {"data_type": "bigint", "nullable": True},
    "utc_date": {"data_type": "timestamp", "nullable": True},
    "status": {"data_type": "text", "nullable": True},
    "matchday": {"data_type": "bigint", "nullable": True},
    "stage": {"data_type": "text", "nullable": True},
    "last_updated": {"data_type": "timestamp", "nullable": True},
    "area_id": {"data_type": "bigint", "nullable": True},
    "season": {"data_type": "bigint", "nullable": True},
    "score__winner": {"data_type": "text", "nullable": True},
    "score__duration": {"data_type": "text", "nullable": True},
    "score__half_time__home": {"data_type": "bigint", "nullable": True},
    "score__half_time__away": {"data_type": "bigint", "nullable": True},
    "score__full_time__home": {"data_type": "bigint", "nullable": True},
    "score__full_time__away": {"data_type": "bigint", "nullable": True},
    "away_team__id": {"data_type": "bigint", "nullable": True},
    "away_team__name": {"data_type": "text", "nullable": True},
    "away_team__short_name": {"data_type": "text", "nullable": True},
    "away_team__tla": {"data_type": "text", "nullable": True},
    "away_team__crest": {"data_type": "text", "nullable": True},
    "home_team__id": {"data_type": "bigint", "nullable": True},
    "home_team__name": {"data_type": "text", "nullable": True},
    "home_team__short_name": {"data_type": "text", "nullable": True},
    "home_team__tla": {"data_type": "text", "nullable": True},
    "home_team__crest": {"data_type": "text", "nullable": True},
    "competition__id": {"data_type": "bigint", "nullable": True},
    "competition__name": {"data_type": "text", "nullable": True},
    "competition__code": {"data_type": "text", "nullable": True},
    "competition__type": {"data_type": "text", "nullable": True},
    "competition__emblem": {"data_type": "text", "nullable": True},
    "_dlt_load_id": {"data_type": "text", "nullable": True},
    "_dlt_id": {"data_type": "text", "nullable": True},
}

TEAMS_COLUMNS = {
    "id": {"data_type": "bigint", "nullable": True},
    "name": {"data_type": "text", "nullable": True},
    "short_name": {"data_type": "text", "nullable": True},
    "tla": {"data_type": "text", "nullable": True},
    "crest": {"data_type": "text", "nullable": True},
    "address": {"data_type": "text", "nullable": True},
    "website": {"data_type": "text", "nullable": True},
    "founded": {"data_type": "bigint", "nullable": True},
    "club_colors": {"data_type": "text", "nullable": True},
    "venue": {"data_type": "text", "nullable": True},
    "last_updated": {"data_type": "timestamp", "nullable": True},
    "area_id": {"data_type": "bigint", "nullable": True},
    "_dlt_load_id": {"data_type": "text", "nullable": True},
    "_dlt_id": {"data_type": "text", "nullable": True},
}

